//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaBodegaDelYankee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compras()
        {
            this.Detalle_Compras = new HashSet<Detalle_Compras>();
        }
    
        public int id_compra { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Compras> Detalle_Compras { get; set; }
    }
}
