//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaBodegaDelYankee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Ventas
    {
        public int id_detalle { get; set; }
        public Nullable<int> id_venta { get; set; }
        public Nullable<int> id_repuesto { get; set; }
        public int cantidad { get; set; }
        public decimal precio_unitario { get; set; }
        public decimal subtotal { get; set; }
    
        public virtual Repuestos Repuestos { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
