//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaBodegaDelYankee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public int id_factura { get; set; }
        public Nullable<int> id_venta { get; set; }
        public string numero_factura { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> monto_total { get; set; }
    
        public virtual Ventas Ventas { get; set; }
    }
}
