//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaBodegaDelYankee.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Repuestos_AmericanosEntities1 : DbContext
    {
        public Repuestos_AmericanosEntities1()
            : base("name=Repuestos_AmericanosEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorias_Repuestos> Categorias_Repuestos { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Compras> Compras { get; set; }
        public virtual DbSet<Detalle_Compras> Detalle_Compras { get; set; }
        public virtual DbSet<Detalle_Ventas> Detalle_Ventas { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Facturas> Facturas { get; set; }
        public virtual DbSet<Movimientos_Inventario> Movimientos_Inventario { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<Repuestos> Repuestos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Vehiculos> Vehiculos { get; set; }
        public virtual DbSet<Ventas> Ventas { get; set; }
    
        public virtual ObjectResult<sp_ClientesPorDireccion_Result> sp_ClientesPorDireccion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ClientesPorDireccion_Result>("sp_ClientesPorDireccion");
        }
    
        public virtual ObjectResult<sp_GananciasTotales_Result> sp_GananciasTotales(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GananciasTotales_Result>("sp_GananciasTotales", fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<sp_InventarioActual_Result> sp_InventarioActual()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_InventarioActual_Result>("sp_InventarioActual");
        }
    
        public virtual ObjectResult<sp_MovimientoInventario_Result> sp_MovimientoInventario(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string tipoMovimiento)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var tipoMovimientoParameter = tipoMovimiento != null ?
                new ObjectParameter("TipoMovimiento", tipoMovimiento) :
                new ObjectParameter("TipoMovimiento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MovimientoInventario_Result>("sp_MovimientoInventario", fechaInicioParameter, fechaFinParameter, tipoMovimientoParameter);
        }
    
        public virtual ObjectResult<sp_RepuestosMasVendidos_Result> sp_RepuestosMasVendidos(Nullable<int> top)
        {
            var topParameter = top.HasValue ?
                new ObjectParameter("Top", top) :
                new ObjectParameter("Top", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RepuestosMasVendidos_Result>("sp_RepuestosMasVendidos", topParameter);
        }
    
        public virtual ObjectResult<sp_TotalVentasPorFecha_Result> sp_TotalVentasPorFecha(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TotalVentasPorFecha_Result>("sp_TotalVentasPorFecha", fechaInicioParameter, fechaFinParameter);
        }
    }
}
