//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaBodegaDelYankee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimientos_Inventario
    {
        public int id_movimiento { get; set; }
        public Nullable<int> id_repuesto { get; set; }
        public string tipo { get; set; }
        public int cantidad { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string referencia { get; set; }
    
        public virtual Repuestos Repuestos { get; set; }
    }
}
